# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Ecuador
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: EcuadorMSP

        # ID to load the MSP definition as
        ID: EcuadorMSP

        MSPDir: ../organizations/peerOrganizations/ecuador.universidades.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('EcuadorMSP.admin', 'EcuadorMSP.peer', 'EcuadorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('EcuadorMSP.admin', 'EcuadorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('EcuadorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('EcuadorMSP.peer')"
